// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterSpec defines the desired state of a ROSA HCP cluster.
// metadata.Name is the client-chosen account-scoped name; metadata.Namespace
// is account-<accountID>.
type ClusterSpec struct {
	// DeleteProtection prevents accidental deletion when enabled.
	// +hyperfleet:write-mode=mutable
	// +optional
	DeleteProtection *bool `json:"deleteProtection,omitempty"`
	// ExpirationTimestamp marks when this cluster should be automatically deleted.
	// +hyperfleet:write-mode=mutable
	// +optional
	ExpirationTimestamp *metav1.Time `json:"expirationTimestamp,omitempty"`
	// Properties are arbitrary key-value pairs for customer metadata.
	// +hyperfleet:write-mode=mutable
	// +kubebuilder:validation:MaxProperties=100
	// +optional
	Properties map[string]string `json:"properties,omitempty"`
	// AdditionalTrustBundle is a PEM-encoded CA bundle used by the cluster.
	// The Platform API accepts this value on writes and redacts it in its responses.
	// +hyperfleet:write-mode=mutable
	// +hyperfleet:response-redact
	// +kubebuilder:validation:MaxLength=1048576
	// +optional
	AdditionalTrustBundle *string `json:"additionalTrustBundle,omitempty"`
	// Tags are customer-defined labels for organizational purposes.
	// +hyperfleet:write-mode=mutable
	// +openshift:enable:FeatureGate=HyperFleetAutoScaling
	// +kubebuilder:validation:MaxProperties=100
	// +optional
	Tags map[string]string `json:"tags,omitempty"`
	// DNSReservationID is the UID of the account-scoped DNSReservation to bind
	// to this Cluster. Immutable after creation.
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:Required
	DNSReservationID string `json:"dnsReservationId"`
	// OidcConfigID is the UID of the account-scoped OidcConfig to use for cluster
	// identity. Empty selects the legacy managed issuer flow. Immutable after creation.
	// +hyperfleet:write-mode=immutable
	// +optional
	OidcConfigID string `json:"oidcConfigId,omitempty"`
	// HostedCluster contains the upstream HyperShift fields, mirrored as
	// passthrough types with per-field visibility and write-mode markers.
	// +kubebuilder:validation:Required
	HostedCluster HostedClusterSpecPassthrough `json:"hostedCluster"`
	// ControlPlaneUpgradePolicy is the control plane upgrade policy defined by the user.
	// +optional
	ControlPlaneUpgradePolicy *ControlPlaneUpgradePolicySpec `json:"controlPlaneUpgradePolicy,omitempty"`
}
